<template>
  <view class="dz-page success-page">
    <view v-if="order" class="success-content"><view class="success-orb">✓</view><strong class="success-title">支付成功</strong><text class="success-subtitle">订单已提交，等待达人接单</text><section class="order-card booking-card"><view class="booking-avatar"><image v-if="order.provider_avatar_url" :src="order.provider_avatar_url" mode="aspectFill" /><view v-else>{{ order.provider_name.slice(0,1) }}</view></view><view><strong>{{ order.provider_name }} · {{ order.service_name }}</strong><text>▣ {{ timeLabel }}</text><text>● {{ addressLabel }}</text></view><view class="paid">实付<strong>¥{{ money(order.payable_amount) }}</strong></view></section><view class="steps"><view class="done"><i>✓</i><text>已支付</text></view><b/><view class="active"><i/><text>待接单</text></view><b/><view><i/><text>待服务</text></view></view><text class="tip">达人将在30分钟内确认接单</text><button class="primary" @tap="viewOrder">查看订单</button><button class="secondary" @tap="goHome">返回首页</button></view>
    <view v-else class="booking-empty">{{ error || '正在加载订单…' }}</view>
  </view>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'; import { onLoad } from '@dcloudio/uni-app'; import { getProviderOrder } from '@/services/orders'; import type { ProviderOrder } from '@/types/api'; import { formatAmount, formatOrderTimeRange, getErrorMessage } from '@/utils/formatters'
const order=ref<ProviderOrder|null>(null),error=ref(''),orderNo=ref('');const money=formatAmount;const timeLabel=computed(()=>order.value?formatOrderTimeRange(order.value.starts_at,order.value.ends_at):'');const addressLabel=computed(()=>order.value?[order.value.meeting_location_name,order.value.meeting_address].filter((value,index,values)=>value&&values.indexOf(value)===index).join('，'):'')
function goHome(){uni.reLaunch({url:'/pages/index/index'})}function viewOrder(){uni.redirectTo({url:`/pages/orders/detail?orderNo=${orderNo.value}`})}
onLoad(async query=>{orderNo.value=typeof query?.orderNo==='string'?query.orderNo:'';try{order.value=(await getProviderOrder(orderNo.value)).data}catch(reason){error.value=getErrorMessage(reason)}})
</script>

<style lang="scss" scoped>
@use '../../styles/tokens.scss' as *; @use '../../styles/booking.scss';
.success-page{min-height:100vh;background:radial-gradient(circle at 50% 10%,#c9fbf7 0,$dz-brand-soft 280rpx,#fff 480rpx)}.success-content{display:flex;flex-direction:column;align-items:center;padding:100rpx 30rpx 40rpx}.success-orb{display:flex;align-items:center;justify-content:center;width:170rpx;height:170rpx;border:18rpx solid #93efea;border-radius:50%;color:$dz-text-inverse;background:$dz-gradient-brand;box-shadow:$dz-shadow-brand;font-size:80rpx}.success-title{margin-top:32rpx;color:$dz-brand-deep;font-size:$dz-fs-title}.success-subtitle{margin-top:14rpx;color:$dz-text-secondary;font-size:$dz-fs-caption}.order-card{position:relative;display:flex;align-items:flex-start;width:100%;margin-top:45rpx;padding:22rpx;box-sizing:border-box}.order-card .booking-avatar{width:78rpx;height:78rpx}.order-card>view:nth-child(2){display:flex;flex:1;flex-direction:column;gap:11rpx;margin-left:16rpx}.order-card>view strong{font-size:$dz-fs-caption}.order-card>view text{color:$dz-text-secondary;font-size:$dz-fs-micro}.paid{position:absolute;right:22rpx;bottom:20rpx;color:$dz-text-secondary;font-size:$dz-fs-micro}.paid strong{margin-left:8rpx;color:$dz-price-primary;font-size:$dz-fs-body-strong!important}.steps{display:flex;align-items:flex-start;width:82%;margin-top:36rpx}.steps view{display:flex;flex-direction:column;align-items:center;gap:9rpx;color:$dz-text-tertiary;font-size:$dz-fs-micro}.steps i{display:block;width:30rpx;height:30rpx;border:3rpx solid $dz-border-subtle;border-radius:50%;font-style:normal;text-align:center;line-height:30rpx}.steps b{flex:1;height:2rpx;margin-top:16rpx;background:$dz-border-subtle}.steps .done,.steps .active{color:$dz-brand-deep}.steps .done i{border-color:$dz-brand-primary;color:$dz-text-inverse;background:$dz-brand-primary}.steps .active i{border-color:$dz-brand-primary}.tip{margin-top:30rpx;padding:12rpx 24rpx;border-radius:$dz-radius-sm;color:$dz-brand-deep;background:$dz-brand-soft;font-size:$dz-fs-caption}.success-content>button{width:100%;height:76rpx;margin:20rpx 0 0;border-radius:$dz-radius-lg;font-size:$dz-fs-body;line-height:76rpx}.success-content>button::after{display:none}.success-content>.primary{border:0;color:$dz-text-inverse;background:$dz-gradient-brand}.success-content>.secondary{border:1rpx solid $dz-brand-primary;color:$dz-brand-deep;background:$dz-surface-card}
</style>
