<template>
  <view class="dz-page list-page"><DzNavBar title="我的收藏" :back-action="goBack"><template #right><text class="dz-navbar-label">{{ providers.length || '' }}</text></template></DzNavBar>
    <main class="dz-container content"><NetworkState v-if="loading" message="正在加载收藏…"/><NetworkState v-else-if="error" :message="error" action-text="重新加载" @action="load"/>
      <DzEmptyState v-else-if="!providers.length" title="还没有收藏达人" description="遇到喜欢的达人，点亮详情页的收藏按钮" />
      <article v-for="item in providers" v-else :key="item.public_id" class="provider" @tap="open(item.public_id)"><image v-if="item.avatar_url" :src="item.avatar_url" mode="aspectFill"/><view v-else class="avatar-fallback">{{item.nickname.slice(0,1)}}</view><view class="copy"><strong>{{item.nickname}} <i v-if="item.verified">✓</i></strong><text>★ {{item.rating}} · 服务{{item.service_count}}次</text><small>{{item.services[0]?.category||'达人服务'}} · {{item.service_city_name}}</small></view><button @tap.stop="remove(item)">取消收藏</button></article>
    </main>
  </view>
</template>
<script setup lang="ts">
import { navigateBackOr } from '@/utils/navigation'
import DzNavBar from '@/components/DzNavBar.vue'
import {onShow} from '@dcloudio/uni-app';import{ref}from'vue';import DzEmptyState from '@/components/DzEmptyState.vue';import NetworkState from '@/components/NetworkState.vue';import{getFavoriteProviders,unfavoriteProvider}from'@/services/engagements';import type{ProviderListItem}from'@/types/api';import{getErrorMessage}from'@/utils/formatters';
const providers=ref<ProviderListItem[]>([]),loading=ref(true),error=ref('');function goBack(){navigateBackOr(()=>uni.reLaunch({url:'/pages/profile/index'}))}function open(id:string){uni.navigateTo({url:`/pages/providers/detail?id=${id}`})}async function load(){loading.value=true;error.value='';try{providers.value=(await getFavoriteProviders()).data.items}catch(e){error.value=getErrorMessage(e)}finally{loading.value=false}}async function remove(item:ProviderListItem){try{await unfavoriteProvider(item.public_id);providers.value=providers.value.filter(value=>value.public_id!==item.public_id);uni.showToast({title:'已取消收藏',icon:'success'})}catch(e){uni.showToast({title:getErrorMessage(e,'操作失败'),icon:'none'})}}onShow(load)
</script>
<style lang="scss" scoped>@use '../../styles/tokens.scss' as *;.list-page{background:$dz-surface-page}.hero{background:linear-gradient(150deg,$dz-brand-soft,#fff)}.nav{display:flex;align-items:center;justify-content:space-between;height:94rpx}.nav view{font-size:58rpx}.nav strong{font-size:$dz-fs-heading}.nav>view,.nav>text{width:64rpx}.nav>text{text-align:right;color:$dz-text-tertiary}.content{padding-top:22rpx}.provider{display:flex;align-items:center;gap:18rpx;margin-bottom:18rpx;padding:20rpx;border-radius:$dz-radius-md;background:$dz-surface-card;box-shadow:$dz-shadow-card}.provider image,.avatar-fallback{width:116rpx;height:116rpx;flex:none;border-radius:$dz-radius-md}.avatar-fallback{display:flex;align-items:center;justify-content:center;color:$dz-brand-deep;background:$dz-brand-soft;font-size:$dz-fs-title}.copy{display:flex;min-width:0;flex:1;flex-direction:column;gap:9rpx}.copy strong{font-size:$dz-fs-body}.copy i{color:$dz-brand-primary;font-style:normal}.copy text,.copy small{color:$dz-text-secondary;font-size:$dz-fs-caption}.provider button{width:110rpx;margin:0;padding:0;border:0;color:$dz-brand-deep;background:$dz-brand-soft;font-size:$dz-fs-caption}.provider button::after{display:none}</style>
